id: PC74C4E5D
initial_creation_type: input
source_metadata:
  title: Gönpo Tseten Rinpoche Series
  language: en
  description: 'Texts by the Nyingma teacher Gönpo Tseten Rinpoche (mgon po tshe brtan,
    1906–1991) of Amdo:'
  volume:
    dd03c0cc29c54106bf1a2365ead1638b:
      title: 'A Bouquet of Uḍumbara Flowers: An Explanation of the Tenth Day'
      parent: Commentaries
    e2801f4d26d34f10b1c721591f40b109:
      title: Prayer to Orgyen Rinpoche Invoking His Wisdom Mind
      parent: Guru Rinpoche Prayers
created_at: '2022-02-28T23:24:46.571502'
last_modified_at: '2022-02-28T23:24:46.571508'
